### ISSUE TITLE
Can raise a `KeyError` on assigning to a slice of a RangeMap

### ISSUE THREAD

**Issue by amagee** [mlenzen/collections-extended#60] opened 2016-08-02 00:32 UTC
Anything using the following pattern:

```
>>> from collections_extended import RangeMap
>>> r = RangeMap()
>>> r[1:1] = 3
>>> r[1:] = 3
```

Exception:

```
/.../site-packages/collections_extended/range_map.py in __setitem__(self, key, value)
    143                 if key.step is not None:
    144                         raise ValueError('Steps aren\'t allowed')
--> 145                 self.set(value, key.start, key.stop)
    146 
    147         def __delitem__(self, index):

/.../site-packages/collections_extended/range_map.py in set(self, value, start, stop)
    109                         stop_value = self.__getitem(stop)
    110                 for key in self._ordered_keys[start_index:stop_index]:
--> 111                         del self._key_mapping[key]
    112                 if stop is not None:
    113                         self._key_mapping[stop] = stop_value

```

**Comment by mlenzen** [comment] 2016-08-06 16:27
The problem is the first step, mapping range `a:b` is for all `a <= x < b` which I guess isn't documented. So 1:1 is an empty range and assigning it either shouldn't do anything or raise a KeyError. 

Is mapping individual values a feature for you? It's a bug in the current implementation,  but I can picture an implementation that keeps track of individual values as a layer on top.

**Closed** 2016-08-06 19:29 UTC
Labels: bug

**Comment by amagee** [comment] 2016-08-06 23:19
The fix is fine; I would have also been happy with doing nothing for setting an empty range. I don't have any need to keep track of individual values independently from values; in my case the bug was discovered as a result of unexpected (and meaningless) data entered by an end user.
